shuffle: roundrobin
# Deployment mode: 'local' for local deployment, 'ansible' for remote deployment via Ansible
deployment_mode: local
config:
  activeEpoch: 18
  keyType: "hash-sig"
  # Optional; omit for default 1 (leanSpec src/lean_spec/subspecs/chain/config.py)
  attestation_committee_count: 1
validators:
  - name: "grandine_0"
    # node id f9e3dfd0eb2e8fb7dfb072b91b23e3286c0fae245cd2c732f4752577f32e5782
    # peer id 16Uiu2HAmErASHzouSQumaetyU18brt4HNUm4151K55ySBQMRLzSS
    privkey: "64a7f5ab53907966374ca23af36392910af682eec82c12e3abbb6c2ccdf39a72"
    # verify /ip4/127.0.0.1/udp/9006/quic-v1/p2p/16Uiu2HAmErASHzouSQumaetyU18brt4HNUm4151K55ySBQMRLzSS
    enrFields:
      ip: "127.0.0.1"
      quic: 9006
    metricsPort: 8086
    apiPort: 5056
    isAggregator: true
    count: 1
  - name: "grandine_1"
    privkey: "bdf953adc161873ba026330c56450453f582e3c4ee6cb713644794bcfdd85fe5"
    enrFields:
      ip: "127.0.0.1"
      quic: 9008
    metricsPort: 8088
    apiPort: 5057
    isAggregator: false
    count: 1
  - name: "ethlambda_0"
    # node id 86cec93353ffcc6f38c9c15becadcb30d1acab21a92b30418110c980a38d9c3d
    # peer id 16Uiu2HAmPV5jU62WtmDkCEmfq1jzbBDkGbHNsDN78gJyvmv2TuC5
    privkey: "299550529a79bc2dce003747c52fb0639465c893e00b0440ac66144d625e066a"
    # verify /ip4/127.0.0.1/udp/9007/quic-v1/p2p/16Uiu2HAmPV5jU62WtmDkCEmfq1jzbBDkGbHNsDN78gJyvmv2TuC5
    enrFields:
      ip: "127.0.0.1"
      quic: 9007
    metricsPort: 8087
    apiPort: 5058
    isAggregator: false
    count: 1
  - name: "grandine_2"
    privkey: "595cd631298140a0f37c6b6bc4189bd105d5f34afc901703ab232c2f09b51b04"
    enrFields:
      ip: "127.0.0.1"
      quic: 9009
    metricsPort: 8089
    apiPort: 5059
    isAggregator: false
    count: 1
  - name: "grandine_3"
    privkey: "76901358d797b696c5909ea4930eecc9ddfe27c775cce9831c60bee629eae08c"
    enrFields:
      ip: "127.0.0.1"
      quic: 9010
    metricsPort: 8090
    apiPort: 5060
    isAggregator: false
    count: 1
  - name: "ethlambda_1"
    privkey: "8571a271d73ba2e77625a5b82e298a8d4d94b1e6c4d2fe073c4209b83a8fbc13"
    enrFields:
      ip: "127.0.0.1"
      quic: 9011
    metricsPort: 8091
    apiPort: 5061
    isAggregator: false
    count: 1
  - name: "ethlambda_2"
    privkey: "678aa31eb504201ae118db966c0e3e25535ccd486973631d951b0927e14c2769"
    enrFields:
      ip: "127.0.0.1"
      quic: 9012
    metricsPort: 8092
    apiPort: 5062
    isAggregator: false
    count: 1
  - name: "lantern_0"
    privkey: "837ff529bbced902cef1948246978daf2065a784fa8bfc67a166f2d00eacfce8"
    enrFields:
      ip: "127.0.0.1"
      quic: 9013
    metricsPort: 8093
    apiPort: 5063
    isAggregator: false
    count: 1
  - name: "lantern_1"
    privkey: "533c974796aa3ebc5e05ea8ba1d216f45b556d608720753841e914a7b3f902cf"
    enrFields:
      ip: "127.0.0.1"
      quic: 9014
    metricsPort: 8094
    apiPort: 5064
    isAggregator: false
    count: 1
  - name: "lantern_2"
    privkey: "f3e257d6edbedb51b848f7a88554897e5f7ce140ea420f56e9032dbc41132b0e"
    enrFields:
      ip: "127.0.0.1"
      quic: 9015
    metricsPort: 8095
    apiPort: 5065
    isAggregator: false
    count: 1
